add error check and print on maven release

diff --git a/src/jobs/maven_release.yml b/src/jobs/maven_release.yml
--- a/src/jobs/maven_release.yml
+++ b/src/jobs/maven_release.yml
@@ -64,6 +64,12 @@ steps:
               MVN_PATH: "<< parameters.mvn_path >>"
             command: |
               RELEASE_VERSION=$(${MVN_PATH} help:evaluate -Dexpression=project.version -q -DforceStdout)
+              
+              if [ $? -eq 1 ]; then
+                echo -e "ERROR!\n"
+                echo $RELEASE_VERSION
+              end
+
               if [[ "${RELEASE_VERSION}" == *"-SNAPSHOT"* ]]; then
                 echo "Ready to merge PR. Current version: ${RELEASE_VERSION}"
                 circleci-agent step halt
